# Generated by Django 6.0.5 on 2026-05-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hit",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
