# Generated by Django 6.0.5 on 2026-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_hit_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlink",
            name="short_url",
            field=models.CharField(blank=True, db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, unique=True
            ),
        ),
    ]
